# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

City.delete_all
Category.delete_all
Group.delete_all

Category.create(name: 'Arts & Culture', meetup_id: 1)
Category.create(name: 'Career & Business', meetup_id: 2)
Category.create(name: 'Cars & Motorcycles', meetup_id: 3)
Category.create(name: 'Community & Environment', meetup_id: 4)
Category.create(name: 'Dancing', meetup_id: 5)
Category.create(name: 'Education & Learning', meetup_id: 6)
Category.create(name: 'Fashion & Beauty', meetup_id: 8)
Category.create(name: 'Fitness', meetup_id: 9)
Category.create(name: 'Food & Drink', meetup_id: 10)
Category.create(name: 'Games', meetup_id: 11)
Category.create(name: 'Movements & Politics', meetup_id: 13)
Category.create(name: 'Health & Wellbeing', meetup_id: 14)
Category.create(name: 'Hobbies & Crafts', meetup_id: 15)
Category.create(name: 'Language & Ethnic Identity', meetup_id: 16)
Category.create(name: 'LGBT', meetup_id: 12)
Category.create(name: 'Lifestyle', meetup_id: 17)
Category.create(name: 'Literature & Writing', meetup_id: 18)
Category.create(name: 'Movies & Film', meetup_id: 20)
Category.create(name: 'Music', meetup_id: 21)
Category.create(name: 'New Age & Spirituality', meetup_id: 22)
Category.create(name: 'Outdoors & Adventure', meetup_id: 23)
Category.create(name: 'Paranormal', meetup_id: 24)
Category.create(name: 'Parents & Family', meetup_id: 25)
Category.create(name: 'Pets & Animals', meetup_id: 26)
Category.create(name: 'Photography', meetup_id: 27)
Category.create(name: 'Religion & Beliefs', meetup_id: 28)
Category.create(name: 'Sci-Fi & Fantasy', meetup_id: 29)
Category.create(name: 'Singles', meetup_id: 30)
Category.create(name: 'Socializing', meetup_id: 31)
Category.create(name: 'Sports & Recreation', meetup_id: 32)
Category.create(name: 'Support', meetup_id: 33)
Category.create(name: 'Tech', meetup_id: 34)
Category.create(name: 'Women', meetup_id: 35)

City.create(name: 'Sydney', country: 'AU', member_count: 21737)
City.create(name: 'Melbourne', country: 'AU', member_count: 19677)
City.create(name: 'Brisbane', country: 'AU', member_count: 15401)
City.create(name: 'Perth', country: 'AU', member_count: 5933)
City.create(name: 'Adelaide', country: 'AU', member_count: 4169)
City.create(name: 'Gold Coast', country: 'AU', member_count: 2363)
City.create(name: 'Canberra', country: 'AU', member_count: 1818)
City.create(name: 'Newcastle', country: 'AU', member_count: 318)
City.create(name: 'Hobart', country: 'AU', member_count: 314)
City.create(name: 'Sunshine Coast', country: 'AU', member_count: 311)

Group.create(category_id: 1 , city_id: 2)
Group.create(category_id: 2 , city_id: 2)
Group.create(category_id: 4 , city_id: 2)
Group.create(category_id: 5 , city_id: 2)
Group.create(category_id: 4 , city_id: 2)
Group.create(category_id: 3 , city_id: 2)
Group.create(category_id: 1 , city_id: 2)
Group.create(category_id: 1 , city_id: 1)
Group.create(category_id: 2 , city_id: 1)
Group.create(category_id: 4 , city_id: 1)
Group.create(category_id: 5 , city_id: 1)
Group.create(category_id: 4 , city_id: 1)
Group.create(category_id: 3 , city_id: 1)
Group.create(category_id: 1 , city_id: 1)
